// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJbYSobQzbTfRW4xIXEnEjMwBOmRJV5Y',
    appId: '1:264412491586:web:a5fc4973cc1b0e97ad22db',
    messagingSenderId: '264412491586',
    projectId: 'pokedex-flutter-85ab7',
    authDomain: 'pokedex-flutter-85ab7.firebaseapp.com',
    storageBucket: 'pokedex-flutter-85ab7.appspot.com',
    measurementId: 'G-8BDZCX2MLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBrQlj1MqaLEqUIdKzDpFaQrTipnon3c',
    appId: '1:264412491586:android:228d9ead7d92090cad22db',
    messagingSenderId: '264412491586',
    projectId: 'pokedex-flutter-85ab7',
    storageBucket: 'pokedex-flutter-85ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi5U6_9ahigwx4DOe9IIT1qRmevABJtME',
    appId: '1:264412491586:ios:6d24a02e6f51d44dad22db',
    messagingSenderId: '264412491586',
    projectId: 'pokedex-flutter-85ab7',
    storageBucket: 'pokedex-flutter-85ab7.appspot.com',
    iosClientId: '264412491586-8nb0hsr1jlueh6s7crpv2dinkkfd1deh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi5U6_9ahigwx4DOe9IIT1qRmevABJtME',
    appId: '1:264412491586:ios:f91d6c6a7ada9f6aad22db',
    messagingSenderId: '264412491586',
    projectId: 'pokedex-flutter-85ab7',
    storageBucket: 'pokedex-flutter-85ab7.appspot.com',
    iosClientId: '264412491586-2tlbtvrs7d9gq1qh38q0fegkanf6f26i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
